apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: lab3
  labels:
    app: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: 914379829654.dkr.ecr.us-east-1.amazonaws.com/my_sql:v0.3
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: pw
        volumeMounts:
        - mountPath: /data/db
          name: mysql-pvc
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - name: mysql
          containerPort: 3306
          protocol: TCP
      volumes:
        - name: mysql-pvc
          persistentVolumeClaim:
            claimName: mysql-pvc